const routerNames = {
    Home: "Home",
    Login: "Login",
    Register: "Register",
    ResetPass: "ResetPass",
    UserActivate: "UserActivate",
    Profile: "Profile",
    ProfileSettings: "ProfileSettings",
    OfficeBase: "OfficeBase",
    OfficeDashboard: "OfficeDashboard",
    OfficeOrders: "OfficeOrders",
    Stars: "Stars",
    StaredTours: "StaredTours",
    Subscribers: "Subscribers",
    Tour: "Tour",
    Tours: "Tours",
    TourForm: "TourForm",
    Country: "Country",
    CountryTours: "CountryTours",
    CountryCategory: "CountryCategory",
    CountrySubCategory: "CountrySubCategory",
    State: "State",
    StateTours: "StateTours",
    StateCategory: "StateCategory",
    StateSubCategory: "StateSubCategory",
    City: "City",
    CityTours: "CityTours",
    CityCategory: "CityCategory",
    CitySubCategory: "CitySubCategory",
    ToursCategory: "ToursCategory",
    ToursSubCategory: "ToursSubCategory",
    Lenta: "Lenta",
    Sights: "Sights",
    CountrySights: "CountrySights",
    StateSights: "StateSights",
    CitySights: "CitySights",
    SightPlace: "SightPlace",
    SightForm: "SightForm",
    Guides: "Guides",
    CountryGuides: "CountryGuides",
    StateGuides: "StateGuides",
    CityGuides: "CityGuides",
    GuideDetail: "GuideDetail",
    GuideHome: "GuideHome",
    GuideForm: "GuideForm",
    About: "About",
    Error404: "Error404"
}


export default routerNames
